
version: '3.9'

services:
  bot-spring:
    container_name: bot-app
    image: pee-java-app:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      - key_bot=
      - server=
    restart: always
